### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by unw9527** [cmu-db/15721-s24-cache1#36]
@unw9527 
- [x] Remove all hard-coded paths. Try to send data paths in HTTP params.
- [x] Change all println to logger.
- [x] Benchmark e2e time.
- [ ] Try to avoid disk I/O when getting data from storage manager.
